// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomaShare.Data;

#nullable disable

namespace SomaShare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508120000_AddUserProfileFields")]
    partial class AddUserProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a simplified snapshot - EF Core will rebuild the full model from the current DbContext
            // The key addition is the Bio and PreferredMeetupCampus columns in ApplicationUser

#pragma warning restore 612, 618
        }
    }
}
